package output

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"cmd-mint/internal/model"
)

const aliasesSHHeader = `# Suggested aliases generated by cmd-mint
# Generated locally from shell history.
# Review before sourcing or copying into your shell config.
# cmd-mint does not install aliases automatically.
`

var safeAliasNamePattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_-]*$`)

func RenderAliasesSH(suggestions []model.AliasSuggestion, maxAliases int) []byte {
	return renderAliasSnippet(suggestions, maxAliases, aliasesSHHeader, quoteShellSingle)
}

func renderAliasSnippet(suggestions []model.AliasSuggestion, maxAliases int, header string, quote func(string) string) []byte {
	if maxAliases < 0 {
		maxAliases = 0
	}

	var buffer bytes.Buffer
	fmt.Fprintln(&buffer, header)
	if maxAliases == 0 {
		return buffer.Bytes()
	}

	written := 0
	for _, suggestion := range aliasFileSuggestions(suggestions, maxAliases) {
		if !safeAliasForFile(suggestion) {
			continue
		}
		fmt.Fprintf(&buffer, "alias %s=%s\n", suggestion.Name, quote(suggestion.Command))
		written++
	}

	if written == 0 {
		fmt.Fprintln(&buffer, "# No safe alias suggestions were found.")
	}

	return buffer.Bytes()
}

func aliasFileSuggestions(suggestions []model.AliasSuggestion, maxAliases int) []model.AliasSuggestion {
	if maxAliases <= 0 {
		return nil
	}

	sorted := sortedAliasSuggestions(suggestions)
	fileSuggestions := make([]model.AliasSuggestion, 0, maxAliases)
	for _, suggestion := range sorted {
		if len(fileSuggestions) >= maxAliases {
			break
		}
		if !suggestion.AliasFileEligible {
			continue
		}
		if suggestion.Confidence == model.ConfidenceLow {
			continue
		}
		fileSuggestions = append(fileSuggestions, suggestion)
	}
	return fileSuggestions
}

func safeAliasForFile(suggestion model.AliasSuggestion) bool {
	if suggestion.Name == "" || suggestion.Command == "" {
		return false
	}
	if !safeAliasNamePattern.MatchString(suggestion.Name) {
		return false
	}
	if strings.ContainsAny(suggestion.Command, "\r\n") {
		return false
	}
	return !containsSensitiveOutputText(suggestion.Command)
}

func quoteShellSingle(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
