package output

import (
	"strings"

	"cmd-mint/internal/model"
)

const aliasesFishHeader = `# Suggested aliases generated by cmd-mint
# Generated locally from shell history.
# Review before sourcing or copying into your fish config.
# cmd-mint does not install aliases automatically.
`

func RenderAliasesFish(suggestions []model.AliasSuggestion, maxAliases int) []byte {
	return renderAliasSnippet(suggestions, maxAliases, aliasesFishHeader, quoteFishSingle)
}

func quoteFishSingle(value string) string {
	if value == "" {
		return "''"
	}

	quoted := strings.ReplaceAll(value, `\`, `\\`)
	quoted = strings.ReplaceAll(quoted, `'`, `\'`)
	return "'" + quoted + "'"
}
